# Generated by Django 5.0.4 on 2024-04-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=100)),
                ('book_author', models.CharField(max_length=100)),
                ('book_desc', models.CharField(max_length=300)),
                ('book_image', models.ImageField(upload_to='media')),
                ('book_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('book_slug', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Books',
            },
        ),
    ]
