# Generated by Django 5.0.4 on 2024-04-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
