# Generated by Django 5.0.4 on 2024-04-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_slug',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
