# Generated by Django 5.0.4 on 2024-04-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_book_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=200)),
                ('article_author', models.CharField(max_length=100)),
                ('article_content', models.TextField()),
                ('article_image', models.ImageField(upload_to='articles_images')),
            ],
            options={
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
