# Generated by Django 5.0.4 on 2024-04-12 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_articles_article_slug_alter_book_book_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='article_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_slug',
            new_name='slug',
        ),
    ]
